# serverless.yml

service: apollo-lambda
provider:
  name: aws
  runtime: nodejs8.10
  package:
    exclude:
    - ./**
    include:
    - dist/**
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: lib/graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
